/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xjJmhphuHcHSM5opr8Lg1q
import {
  createStyleTokensProvider,
  createUseStyleTokens
} from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: xjJmhphuHcHSM5opr8Lg1q/projectModule
import projectcss from "./plasmic.module.css"; // plasmic-import: xjJmhphuHcHSM5opr8Lg1q/projectcss

const data = {
  base: projectcss.plasmic_tokens,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);

export const StyleTokensProvider = createStyleTokensProvider(
  data,
  _useGlobalVariants
);
