/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xjJmhphuHcHSM5opr8Lg1q
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariants_1YhSe8CgNtxT } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 1YHSe8CGNtxT/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_1YhSe8CgNtxT
});
